import React from "react";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";

import { Toaster } from "@/components/ui/sonner";

import { ClerkProvider } from "@clerk/nextjs";
import { QueryProviders } from "@/providers/query-provider";
import { SheetProvider } from "@/providers/sheet-provider";

const montserrat = Montserrat({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body className={montserrat.className}>
          <QueryProviders>
            <SheetProvider />
            <Toaster richColors theme="light" />
            {children}
          </QueryProviders>
        </body>
      </html>
    </ClerkProvider>
  );
}
